import type { Config } from 'tailwindcss'

export default <Config>{
  content: [],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#5ade9d',
        'on-secondary-container': '#3e6c52',
        'error-container': '#ffdad6',
        'primary-container': '#2dba7d',
        'surface-variant': '#e1e3e2',
        'surface-tint': '#006c45',
        'surface-container': '#eceeed',
        'outline-variant': '#bccabe',
        'on-surface-variant': '#3d4a41',
        'surface': '#f8faf9',
        'tertiary-fixed-dim': '#ffb3b4',
        'secondary-fixed': '#bceece',
        'surface-container-high': '#e6e9e8',
        'inverse-primary': '#5ade9d',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#a1d2b3',
        'tertiary-fixed': '#ffdad9',
        'surface-container-lowest': '#ffffff',
        'primary': '#006c45',
        'on-background': '#191c1c',
        'tertiary': '#a43942',
        'on-primary': '#ffffff',
        'on-surface': '#191c1c',
        'secondary-container': '#b9ebcb',
        'inverse-surface': '#2e3131',
        'on-primary-fixed-variant': '#005233',
        'surface-container-highest': '#e1e3e2',
        'surface-container-low': '#f2f4f3',
        'on-secondary': '#ffffff',
        'secondary': '#3a674e',
        'on-tertiary-container': '#731421',
        'error': '#ba1a1a',
        'on-secondary-fixed-variant': '#214f38',
        'on-secondary-fixed': '#002112',
        'background': '#f8faf9',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'inverse-on-surface': '#eff1f0',
        'primary-fixed': '#78fbb8',
        'on-tertiary-fixed': '#40000a',
        'surface-dim': '#d8dada',
        'on-tertiary-fixed-variant': '#84222c',
        'outline': '#6d7a70',
        'surface-bright': '#f8faf9',
        'on-primary-container': '#004429',
        'on-primary-fixed': '#002112',
        'tertiary-container': '#fd7d83',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
}
